services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: my-app
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: kdfWe23k!j0js
    volumes:
      - my-app-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"
volumes:
    my-app-data: