services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - my-app-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"
volumes:
    my-app-data: